name: SmartInvs
version: 1.2.7
author: MinusKube
website: https://github.com/MinusKube/SmartInvs
main: fr.minuskube.inv.SmartInvsPlugin
description: Inventory API for your Bukkit Plugins. Maj By TokyoSlayer
